ability					=	activated-ability / triggered-ability / unknown-ability
activated-ability		= 	cost *[",", cost] ":" effect
triggered-ability		=	trigger-condition "," effect
unknown-ability			=	ANY
cost					=	tap-cost, untap-cost, mana-cost, life-cost, sacrifice-cost
tap-cost				=	"{T}"
untap-cost				=	"{Q}"
mana-cost				=	["{X}" ] ["{" digit "}" ] *mana-symbol
mana-symbol				=	"{U}" / "{B}" / "{W}" / "{R}" / "{G}"
life-cost				=	"Pay" digit "life"
sacrifice-cost			=	"Sacrifice" (sacrifice-permanents / THIS)
sacrifice-permanents	=	("a" / "two" / "three" / "all") permanent
permanent				=	land / creature / artifact / enchantment
land					=	["basic" / "non basic"] "land" / "mountain" / "island" / "swamp" / "plains"
creature				=	"creature"
artifact				=	"artifact"
enchantment				=	"enchantment"
trigger-condition		=	("when" / "whenever" / "at") ANY_NON_COMMA
effect					=	ANY